import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/set';
import 'core-js/es6/map';
import 'core-js/fn/promise';
